### ISSUE TITLE
Add auto scroll feature.

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#1]
Currently, the Chatting page cannot scroll to the bottom automatically when new messages are added. You need to implement this feature.**FYI: It can be done with just one line of code!**

**Comment by adtoria** [comment]
Claim

**Comment by homewardgamer** [comment]
Assigned to @adtoria !

**Comment by Ayushi181** [comment]
Claim

**Comment by sravyakaviti** [comment]
Claim

**Comment by shlesh** [comment]
claim

**Comment by rankit2001** [comment]
claim
