### ISSUE TITLE
Correct time on heroku deployment

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#158]
As of now the time showing in the Heroku deployment of the web App is wrong. Fix that issue. Provide a live Heroku link with the PR.

**Comment by batflarrow** [comment]
Claim

**Comment by karankc23** [comment]
Claim

**Comment by homewardgamer** [comment]
> > Go ahead @batflarrow
> > The time you are talking about here is the message time right..?

Yes
