### ISSUE TITLE
Show online Users at the front page

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#170]
Show the number of online users in a room at the front page in front of the respective room name in the drop-down menu.Also don't forget to share a live heroku link when you create the PR.

**Comment by shlesh** [comment]
sed

**Comment by raghavgoel25** [comment]
claim

**Comment by diyawaghmare** [comment]
claim

**Comment by varunKT001** [comment]
Claim

**Comment by homewardgamer** [comment]
Go ahead @raghavgoel25

**Comment by batflarrow** [comment]
Hey @homewardgamer just wanted to confirm that these number of users should  also update in real time i.e. Should i establish a socket connection on the landing page itself or should the user just receive the number of users one time on landing on the page via api and update on refresh only..
