### ISSUE TITLE
Remove extra padding in chat container

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#175]
There is a lot of extra padding int the chat container of the main page. Fix that.
![Screenshot from 2021-10-11 09-26-06](https://user-images.githubusercontent.com/73935799/136731134-e7a8ea30-e849-468f-85cf-3cbaa73922a3.png)

**Comment by jalanprakhar** [comment]
:(

**Comment by homewardgamer** [comment]
> claim

go ahead @VineethKumarM
