### ISSUE TITLE
Fix theme transition

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#182]
The transition on the first page is not consistent, the background changes faster than the text and thus the transitions look weird. Also when changing front dark to light mode the background changes abruptly without any effect. Fix that.

**Comment by ashutosh3027** [comment]
claim

**Comment by homewardgamer** [comment]
@AgrimVerma  you have 3 issues assigned to you at the moment

**Comment by homewardgamer** [comment]
Assigned to @ashutosh3027
