### ISSUE TITLE
Redesign the complete UI of the GeekChat app

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#188]
In this Issue, you have to redesign the complete UI of the GeekChat app, this includes both the front page and the main page. You have to redesign it using [Figma](https://www.figma.com/). Check the **Design** folder for the `tempate.json` file.

You have to follow the template and create a file named `<GITHUB_USERNAME>.json`. In the PR that you will create, include screenshots of the redesign also.
- Designs need to be minimal and intuitive.
- You have to make designs for both dark and light mode.
- **Only the top 3 designs will be merged.**
- The deadline to submit your PR is 16th Oct.
- This is a open for all issue so **no need to claim it**.
All the best!

**Comment by hotblooded058** [comment]
@homewardgamer sir close this issue and review PR now please
