### ISSUE TITLE
Show typing status of Users.

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#205]
In this Issue, you have to find a way so that if a user is typing a message, then it shows that `XYZ is typing ...` with slight animation of three dots. Also if more than one user is typing a message it should show `User1, User2 are typing ...`
For more than 3 Users it should show `Many people are typing ...` just like in discord. Implement this feature with a nice UI and understandable code.

**Comment by varunKT001** [comment]
claim
