### ISSUE TITLE
Add Edit Message Feature

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#213]
Allow users to edit the messages sent by them, also, update the time of the message with the update time and add a small `(edited)` text along with the message. Implement this feature keeping in mind the current UI of the webApp.

**Comment by VineethKumarM** [comment]
claim

**Comment by homewardgamer** [comment]
Assigned to @shlesh

**Comment by homewardgamer** [comment]
Issue open for claims
