### ISSUE TITLE
Apply MVC architectural pattern

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#252]
Apply the standard MVC pattern and differentiate the `app.js` code into its separate files.

**Comment by homewardgamer** [comment]
Updates @shlesh ?

**Comment by shlesh** [comment]
Will make the PR soon @homewardgamer sir!

**Comment by homewardgamer** [comment]
Yeah submit it by today 3pm , already a lot of time has been given @shlesh

**Comment by shlesh** [comment]
> 
> 
> Yeah submit it by today 3pm , already a lot of time has been given @shlesh

true :(
WIll do for sure!!
