### ISSUE TITLE
Allow Users to create new rooms.

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#253]
In the Issue, you have to allow Users to create new rooms. These rooms will be temporary and will remain active on the website until there is no one in the room.

**Comment by homewardgamer** [comment]
Updates @diyawaghmare ?

**Comment by homewardgamer** [comment]
Issue open for claims!

**Comment by varunKT001** [comment]
claim

**Comment by homewardgamer** [comment]
Assigned to @varunKT001
