### ISSUE TITLE
Improve front page layout

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#254]
Improve the Frontpage layout. Make the front page layout better and more styled. If the work done is good Points can be increased too.

**Comment by prakhar011** [comment]
claim

**Comment by KIRTEE-TECH** [comment]
@homewardgamer kindly unassign me

**Comment by varunKT001** [comment]
@homewardgamer sir can you assign me pls

**Comment by homewardgamer** [comment]
open for claims!

**Comment by varunKT001** [comment]
claim

**Comment by homewardgamer** [comment]
Assigned to @varunKT001
