### ISSUE TITLE
Make front page responsive

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#3]
Currently, the page is overflowing in mobile view. FIx the webpage so that it can be responsive!

**Comment by prakhar011** [comment]
I'll work on it

**Comment by adtoria** [comment]
Claim

**Comment by homewardgamer** [comment]
Assigned to @prakhar011 !

**Comment by rankit2001** [comment]
claim

**Comment by yadav-rohit** [comment]
i would like to work on it

**Comment by Dheeraj096** [comment]
I want to work on that

**Comment by shlesh** [comment]
nicee

**Comment by homewardgamer** [comment]
Issue is open to claims

**Comment by batflarrow** [comment]
Claim

**Comment by homewardgamer** [comment]
> > You are assigned 4 issues, you can't claim any more @batflarrow
> 
> But if i already have a pr open for them still I can't claim?

No you can't

**Comment by homewardgamer** [comment]
Issue Open to claims!

**Comment by batflarrow** [comment]
> > You are assigned 4 issues, you can't claim any more @batflarrow 
> 
> But if i already have a pr open for them still I can't claim? 

    Claim

**Comment by batflarrow** [comment]
Claim

**Comment by VineethKumarM** [comment]
Claim
