### ISSUE TITLE
Suggest new Issues here.

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#6]
Suggest some bugs or new features that can be added here!

**Comment by prakhar011** [comment]
make the online users section update in real time

**Comment by homewardgamer** [comment]
> make the online users section update in real time

Yepp that's intentionally left like that. For you guys to resolve later in the month.😄

**Comment by codesanta142** [comment]
mobile view

**Comment by homewardgamer** [comment]
> No way send messages

Currently, the webApp supports message sending and receiving

**Comment by batflarrow** [comment]
Create Models to store chat history for a given room

**Comment by batflarrow** [comment]
Storing username as well as last room in local storage the first time a user enters a room and then using this information (if present) when a user reaches the website again

**Comment by homewardgamer** [comment]
> Storing username as well as last room in local storage the first time a user enters a room and then using this information (if present) when a user reaches the website again

Looks like a nice issue , though it will require the use of the database.I will look into it and then raise the issue.

**Comment by batflarrow** [comment]
> > Storing username as well as last room in local storage the first time a user enters a room and then using this information (if present) when a user reaches the website again
> 
> Looks like a nice issue, though it will require the use of the database. I will look into it and then raise the issue. Will you be able to work on it?

Yeah, sure I will be able to work on it, although according to me a database is not required it can be stored in the local storage of a user's browser itself.

**Comment by batflarrow** [comment]
> > > Storing username as well as last room in local storage the first time a user enters a room and then using this information (if present) when a user reaches the website again
> > 
> > 
> > Looks like a nice issue, though it will require the use of the database. I will look into it and then raise the issue. Will you be able to work on it?
> 
> Yeah, sure I will be able to work on it, although according to me a database is not required it can be stored in the local storage of a user's browser itself. But I will be able to work on it even if we store it in a database (if required).

**Comment by homewardgamer** [comment]
> > > Storing username as well as last room in local storage the first time a user enters a room and then using this information (if present) when a user reaches the website again
> > 
> > 
> > Looks like a nice issue, though it will require the use of the database. I will look into it and then raise the issue. Will you be able to work on it?
> 
> Yeah, sure I will be able to work on it, although according to me a database is not required it can be stored in the local storage of a user's browser itself.

Fine then I will create an issue and assign it to you.

**Comment by batflarrow** [comment]
> > > > Storing username as well as last room in local storage the first time a user enters a room and then using this information (if present) when a user reaches the website again
> > > 
> > > 
> > > Looks like a nice issue, though it will require the use of the database. I will look into it and then raise the issue. Will you be able to work on it?
> > 
> > 
> > Yeah, sure I will be able to work on it, although according to me a database is not required it can be stored in the local storage of a user's browser itself.
> 
> Fine then I will create an issue and assign it to you.

Great!

**Comment by homewardgamer** [comment]
@batflarrow The issue has been created. Claim it

**Comment by batflarrow** [comment]
> @batflarrow The issue has been created. Claim it

I have claimed it..

**Comment by Palak-2109** [comment]
Whichever room we join..it shows web development only in the room name section

**Comment by homewardgamer** [comment]
> Whichever room we join..it shows web development only in the room name section

Yepp that's intentionally left like that. For you guys to resolve later in the month.😄

**Comment by try-catch-stack** [comment]
Add format script to format all javascript files using prettier to maintain consistency in the codebase and help in reading code efficiently.

**Comment by KarishmaVanwari** [comment]
Custom scrollbar @homewardgamer

**Comment by homewardgamer** [comment]
Will

> Custom scrollbar @homewardgamer

Will look into that

**Comment by homewardgamer** [comment]
> Add format script to format all javascript files using prettier (before committing) to maintain consistency in the codebase and help in reading code efficiently.

No need for that since the code is not that much.

**Comment by daniel-aracquine** [comment]
A location button to allow the users to share their current location would be nice.

**Comment by daniel-aracquine** [comment]
Also whenever a new user joins it shows a user entered the chat. It would be good if instead of a user it shows their name like brad has entered the chat

**Comment by homewardgamer** [comment]
> Also whenever a new user joins it shows a user entered the chat. It would be good if instead of a user it shows their name like brad has entered the chat

Would you like to work on this issue?

**Comment by try-catch-stack** [comment]
> > Also whenever a new user joins it shows a user entered the chat. It would be good if instead of a user it shows their name like brad has entered the chat
> 
> Would you like to work on this issue?

I would like to claim this issue.

**Comment by daniel-aracquine** [comment]
> > Also whenever a new user joins it shows a user entered the chat. It would be good if instead of a user it shows their name like brad has entered the chat
> 
> Would you like to work on this issue?

Yes sir i want to work on this issue

**Comment by daniel-aracquine** [comment]
> > > Also whenever a new user joins it shows a user entered the chat. It would be good if instead of a user it shows their name like brad has entered the chat
> > 
> > 
> > Would you like to work on this issue?
> 
> Yes sir i want to work on this issue

@homewardgamer can u please create an issue for this so i can start working.

**Comment by homewardgamer** [comment]
> > > > Also whenever a new user joins it shows a user entered the chat. It would be good if instead of a user it shows their name like brad has entered the chat
> > > 
> > > 
> > > Would you like to work on this issue?
> > 
> > 
> > Yes sir i want to work on this issue
> 
> @homewardgamer can u please create an issue for this so i can start working.

Yeah sure !

**Comment by homewardgamer** [comment]
Claim the issue @daniel-aracquine

**Comment by daniel-aracquine** [comment]
Multiple users with the same username can join the chat room. It will most certainly cause confusion. I would like to work on this issue so that there are no duplicate usernames in a chat room.

**Comment by homewardgamer** [comment]
That's already a planned Issue for the upcoming days 

> Multiple users with the same username can join the chat room. It will most certainly cause confusion. I would like to work on this issue so that there are no duplicate usernames in a chat room.

**Comment by homewardgamer** [comment]
> Custom scrollbar @homewardgamer

Do you want to work on this?

**Comment by KarishmaVanwari** [comment]
> > Custom scrollbar @homewardgamer
> 
> Do you want to work on this?

Yeah, sure! @homewardgamer

**Comment by homewardgamer** [comment]
> > > Custom scrollbar @homewardgamer
> > 
> > 
> > Do you want to work on this?
> 
> Yeah, sure! @homewardgamer

There are some U/I improvements that needs to be done after which I will open the issue.

**Comment by homewardgamer** [comment]
@KarishmaVanwari Are you still ready to work on this?

> > > Custom scrollbar @homewardgamer
> > 
> > 
> > Do you want to work on this?
> 
> Yeah, sure! @homewardgamer

**Comment by KarishmaVanwari** [comment]
> @KarishmaVanwari Are you still ready to work on this?
> 
> > > > Custom scrollbar @homewardgamer
> > > 
> > > 
> > > Do you want to work on this?
> > 
> > 
> > Yeah, sure! @homewardgamer

Yeah, for sure! You can assign me the issue once created. I will work on it. @homewardgamer

**Comment by homewardgamer** [comment]
> > @KarishmaVanwari Are you still ready to work on this?
> > > > > Custom scrollbar @homewardgamer
> > > > 
> > > > 
> > > > Do you want to work on this?
> > > 
> > > 
> > > Yeah, sure! @homewardgamer
> 
> Yeah, for sure! You can assign me the issue once created. I will work on it. @homewardgamer @varunKT001

Claim the issue
