### ISSUE TITLE
Implement rooms feature.

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#87]
Currently, different rooms functionality is not present in the chat app. The final result should be that one person that enters the room can talk and chat with only those people that are present in the same room, also display the room name in the **Room Name** section of the main page. Implement that feature with proper code structuring.

**Comment by batflarrow** [comment]
claim

**Comment by raghavgoel25** [comment]
Claim

**Comment by homewardgamer** [comment]
Go ahead @batflarrow .

**Comment by prxtikk-18** [comment]
claim
