### ISSUE TITLE
Add a dark mode feature.

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#90]
Implement a dark and light theme feature. The dark mode should look good, not just the inversion of colours, also store the mode preference in the `local storage` also.

**Comment by codesanta142** [comment]
claim

**Comment by prxtikk-18** [comment]
claim

**Comment by homewardgamer** [comment]
Go ahead @codesanta142

**Comment by isharawat** [comment]
Claim

**Comment by prxtikk-18** [comment]
claim

**Comment by Dheeraj096** [comment]
claim
