### ISSUE TITLE
Change the message sending div.

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Geek-Chat#92]
Currently, the message sending input box and the send button is square-shaped and of an old theme. I want you to turn it more trendy. Turn the send button into a [Floating Action Button](https://material.io/components/buttons-floating-action-button) with an arrow symbol and make the input element rounder.Use the Material UI FAB buttons only.Also make sure you implement the colours for dark mode also.

**Comment by isharawat** [comment]
Claim

**Comment by prxtikk-18** [comment]
claim

**Comment by homewardgamer** [comment]
Go ahead @isharawat

**Comment by Dheeraj096** [comment]
claim

**Comment by codelord09** [comment]
claim

**Comment by batflarrow** [comment]
Can i Claim? 😂

**Comment by Ksathwik03** [comment]
Claim

**Comment by garvitchittora** [comment]
@batflarrow 

https://github.com/opencodeiiita/Geek-Editor-Backend/issues/71
https://github.com/opencodeiiita/Shopping-Cart/issues/1
https://github.com/opencodeiiita/Shopping-Cart/issues/2
https://github.com/opencodeiiita/Warriors/issues/16

**Comment by homewardgamer** [comment]
Issue is now open to claims

**Comment by batflarrow** [comment]
Claim

**Comment by batflarrow** [comment]
Is it open for all..?

**Comment by shlesh** [comment]
chorro bro dedo XD

**Comment by shlesh** [comment]
@homewardgamer sorry that was another issue
![image](https://user-images.githubusercontent.com/76761060/136582345-69e3fe93-5712-4dc3-bb00-e5079847c5c0.png)
these are my currently assigned ones
sorry for the inconvenience

**Comment by homewardgamer** [comment]
Since @shlesh  is assigned less than 3 Issues, so I have to assign it to him @batflarrow

**Comment by batflarrow** [comment]
> Since @shlesh  is assigned less than 3 Issues, so I have to assign it to him @batflarrow 

Ohk cool but just a general doubt,. We can claim if a user asks to be unassigned or unassigns himslef even before mentor says they are up for claimimg right..?

**Comment by homewardgamer** [comment]
Issue open to claims.

**Comment by daniel-aracquine** [comment]
Claim

**Comment by homewardgamer** [comment]
updates @daniel-aracquine ?

**Comment by VineethKumarM** [comment]
Is the issue open for claims? I want to work on it.

**Comment by homewardgamer** [comment]
Issue open for claims.

**Comment by homewardgamer** [comment]
You already have one issue assigned in this repo. @varunKT001

**Comment by varunKT001** [comment]
sed 😓😓

**Comment by KIRTEE-TECH** [comment]
claim

**Comment by homewardgamer** [comment]
> or could i use any other/better library for this?

No you have to use only material.io
